language: objective-c

matrix:
  include:
    - env: OSX=10.12
      os: osx
      osx_image: xcode8.1
      rvm: system
    - env: OSX=10.11
      os: osx
      osx_image: xcode7.3
      rvm: system
    - env: OSX=10.10
      os: osx
      osx_image: xcode6.4
      rvm: system

before_install:
  - brew update > /dev/null || brew update > /dev/null

install:
  - mkdir -p $(brew --repo)/Library/Taps/personalrobotics
  - ln -s $PWD $(brew --repo)/Library/Taps/personalrobotics/homebrew-tap
  - brew tap --repair

script:
  - brew audit `ls $(brew --repo)/Library/Taps/personalrobotics/homebrew-tap/*.rb`
  - brew style `ls $(brew --repo)/Library/Taps/personalrobotics/homebrew-tap/*.rb`
  - brew fetch `ls $(brew --repo)/Library/Taps/personalrobotics/homebrew-tap/*.rb` | grep -v '%$'
  - brew unpack --patch `ls $(brew --repo)/Library/Taps/personalrobotics/homebrew-tap/*.rb`
